#!/usr/bin/env python3
"""
Validates agents.config.yaml against schemas/agent-manifest.schema.json, then generates
typed, always-in-sync bindings for both the Python and Node/TypeScript agent runtimes.

This is the one script that makes the two halves of the stack a single build system
instead of two separate projects: nobody hand-types an agent id or topic name into
Python OR Node code. It's generated from here, every time `make build` runs.
"""
import json
import sys
from pathlib import Path

import yaml

try:
    from jsonschema import validate, ValidationError

    HAVE_JSONSCHEMA = True
except ImportError:  # pragma: no cover - offline/minimal environments
    HAVE_JSONSCHEMA = False

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "agents.config.yaml"
SCHEMA_PATH = ROOT / "schemas" / "agent-manifest.schema.json"
PY_OUT = ROOT / "python" / "src" / "d3rac_agents" / "_generated_manifest.py"
TS_OUT = ROOT / "node" / "src" / "config" / "generatedManifest.ts"

HEADER = "Auto-generated by scripts/build_manifest.py from agents.config.yaml. Do not edit by hand."

REQUIRED_AGENT_FIELDS = ("id", "runtime", "kind", "entrypoint")
VALID_RUNTIMES = {"python", "node"}
VALID_KINDS = {"data", "analysis", "coordination"}


def _minimal_validate(manifest: dict) -> None:
    """Dependency-free fallback validation, used when `jsonschema` isn't installed
    (e.g. offline environments). Install `jsonschema` for the full schema check --
    this only catches the most common authoring mistakes."""
    errors = []
    if "agents" not in manifest or not manifest["agents"]:
        errors.append("'agents' must be a non-empty list")
    seen_ids = set()
    for i, agent in enumerate(manifest.get("agents", [])):
        for field in REQUIRED_AGENT_FIELDS:
            if field not in agent:
                errors.append(f"agents[{i}] missing required field '{field}'")
        if agent.get("runtime") not in VALID_RUNTIMES:
            errors.append(f"agents[{i}].runtime must be one of {VALID_RUNTIMES}")
        if agent.get("kind") not in VALID_KINDS:
            errors.append(f"agents[{i}].kind must be one of {VALID_KINDS}")
        agent_id = agent.get("id")
        if agent_id in seen_ids:
            errors.append(f"duplicate agent id '{agent_id}'")
        seen_ids.add(agent_id)
    if errors:
        for e in errors:
            print(f"agents.config.yaml: {e}", file=sys.stderr)
        sys.exit(1)


def load_manifest() -> dict:
    manifest = yaml.safe_load(MANIFEST_PATH.read_text())
    if HAVE_JSONSCHEMA:
        schema = json.loads(SCHEMA_PATH.read_text())
        try:
            validate(instance=manifest, schema=schema)
        except ValidationError as e:
            print(f"agents.config.yaml failed validation: {e.message}", file=sys.stderr)
            sys.exit(1)
    else:
        print("note: 'jsonschema' not installed, using minimal built-in validation", file=sys.stderr)
        _minimal_validate(manifest)
    return manifest


def write_python(manifest: dict) -> None:
    agents = manifest["agents"]
    lines = [
        f"# {HEADER}",
        "from typing import Any",
        "",
        f'BUS_TRANSPORT = "{manifest["bus"]["transport"]}"',
        f'BUS_CHANNEL_PREFIX = "{manifest["bus"]["channel_prefix"]}"',
        f'BUS_FILE_DIR = "{manifest["bus"].get("file", {}).get("dir", "data/bus")}"',
        f'BUS_REDIS_URL = "{manifest["bus"].get("redis", {}).get("url", "")}"',
        "",
        "AGENTS: dict[str, dict[str, Any]] = {",
    ]
    for a in agents:
        lines.append(f'    "{a["id"]}": {json.dumps(a)},')
    lines.append("}")
    lines.append("")
    lines.append("PYTHON_AGENT_IDS: list[str] = [")
    for a in agents:
        if a["runtime"] == "python":
            lines.append(f'    "{a["id"]}",')
    lines.append("]")
    lines.append("")
    PY_OUT.parent.mkdir(parents=True, exist_ok=True)
    PY_OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {PY_OUT.relative_to(ROOT)}")


def write_typescript(manifest: dict) -> None:
    agents = manifest["agents"]
    lines = [
        f"// {HEADER}",
        "export interface AgentDef {",
        "  id: string;",
        "  runtime: 'python' | 'node';",
        "  kind: 'data' | 'analysis' | 'coordination';",
        "  entrypoint: string;",
        "  description?: string;",
        "  subscribes?: string[];",
        "  publishes?: string[];",
        "  config?: Record<string, unknown>;",
        "}",
        "",
        f"export const BUS_TRANSPORT: 'file' | 'redis' = '{manifest['bus']['transport']}';",
        f"export const BUS_CHANNEL_PREFIX = '{manifest['bus']['channel_prefix']}';",
        f"export const BUS_FILE_DIR = '{manifest['bus'].get('file', {}).get('dir', 'data/bus')}';",
        f"export const BUS_REDIS_URL = '{manifest['bus'].get('redis', {}).get('url', '')}';",
        "",
        "export const AGENTS: Record<string, AgentDef> = " + json.dumps(
            {a["id"]: a for a in agents}, indent=2
        ) + ";",
        "",
        "export const NODE_AGENT_IDS: string[] = " + json.dumps(
            [a["id"] for a in agents if a["runtime"] == "node"]
        ) + ";",
        "",
    ]
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.write_text("\n".join(lines))
    print(f"wrote {TS_OUT.relative_to(ROOT)}")


def main() -> None:
    manifest = load_manifest()
    write_python(manifest)
    write_typescript(manifest)
    print(f"validated {len(manifest['agents'])} agents from agents.config.yaml")


if __name__ == "__main__":
    main()
