# Auto-generated by scripts/build_manifest.py from agents.config.yaml. Do not edit by hand.
from typing import Any

BUS_TRANSPORT = "file"
BUS_CHANNEL_PREFIX = "d3rac"
BUS_FILE_DIR = "data/bus"
BUS_REDIS_URL = "redis://localhost:6379"

AGENTS: dict[str, dict[str, Any]] = {
    "hazard-ingestor": {"id": "hazard-ingestor", "runtime": "python", "kind": "data", "entrypoint": "d3rac_agents.hazard_agent:HazardAgent", "description": "Ingests hazard-probability signals (weather, seismic, flood feeds).", "publishes": ["hazard.signal"]},
    "exposure-scorer": {"id": "exposure-scorer", "runtime": "python", "kind": "data", "entrypoint": "d3rac_agents.exposure_agent:ExposureAgent", "description": "Computes exposure factor E(c) per community from population/asset data.", "subscribes": ["community.registry"], "publishes": ["exposure.score"]},
    "vulnerability-scorer": {"id": "vulnerability-scorer", "runtime": "python", "kind": "data", "entrypoint": "d3rac_agents.vulnerability_agent:VulnerabilityAgent", "description": "Computes vulnerability index V(c) from infrastructure + socioeconomic data.", "subscribes": ["community.registry"], "publishes": ["vulnerability.index"]},
    "risk-model": {"id": "risk-model", "runtime": "python", "kind": "analysis", "entrypoint": "d3rac_agents.risk_model:RiskModelAgent", "description": "Implements R(c,t) = H(t) * E(c) * V(c); fires when R crosses theta.", "subscribes": ["hazard.signal", "exposure.score", "vulnerability.index"], "publishes": ["risk.score"], "config": {"theta": 0.15}},
    "brainbox": {"id": "brainbox", "runtime": "python", "kind": "analysis", "entrypoint": "d3rac_agents.brainbox:BrainboxAgent", "description": "Central LLM-backed controller. Reasons over all triggered risk.score events with Claude and publishes one authoritative brainbox.directive per community, which response-coordinator/community-alerter/contract-trigger read first (falling back to their own built-in rules if brainbox produced no directive for that community).\n", "subscribes": ["risk.score"], "publishes": ["brainbox.directive"], "config": {"model": "claude-sonnet-4-6", "requires_env": "ANTHROPIC_API_KEY"}},
    "response-coordinator": {"id": "response-coordinator", "runtime": "node", "kind": "coordination", "entrypoint": "agents/coordinationAgent", "description": "Drafts a milestone-based response plan once risk crosses threshold.", "subscribes": ["risk.score", "brainbox.directive"], "publishes": ["response.plan"]},
    "community-alerter": {"id": "community-alerter", "runtime": "node", "kind": "coordination", "entrypoint": "agents/alertAgent", "description": "Notifies NGO/community coordinator channels (zero blockchain literacy required).", "subscribes": ["risk.score", "response.plan", "brainbox.directive"], "publishes": ["alert.sent"]},
    "contract-trigger": {"id": "contract-trigger", "runtime": "node", "kind": "coordination", "entrypoint": "agents/contractTriggerAgent", "description": "Calls into TRON/Casper contracts to release milestone-based funds.", "subscribes": ["response.plan", "brainbox.directive"], "publishes": ["fund.release.requested"], "config": {"tron_contracts_dir": "contracts/tron", "casper_contracts_dir": "contracts/casper"}},
}

PYTHON_AGENT_IDS: list[str] = [
    "hazard-ingestor",
    "exposure-scorer",
    "vulnerability-scorer",
    "risk-model",
    "brainbox",
]

